// Code generated by tools/database/compile_forever_sets.py; DO NOT EDIT.
package core

import (
	"github.com/wowsims/classic/sim/core/proto"
	"github.com/wowsims/classic/sim/core/stats"
)

var foreverEquipmentSets = map[int32]foreverEquipmentSet{
	1: {Name: "The Gladiator", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.AttackPower: 20, stats.RangedAttackPower: 20}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1, stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	124: {Name: "Deathbone Guardian", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Defense: 3}, SpiritRegen: 0},
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		4: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 5, stats.FireResistance: 5, stats.FrostResistance: 5, stats.NatureResistance: 5, stats.ShadowResistance: 5}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	141: {Name: "Volcanic Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	142: {Name: "Stormshroud Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		4: {Supported: true, Stats: stats.Stats{stats.AttackPower: 14, stats.RangedAttackPower: 14}, SpiritRegen: 0},
	}},
	143: {Name: "Devilsaur Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 2, stats.SpellHit: 2}, SpiritRegen: 0},
	}},
	144: {Name: "Ironfeather Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.HealingPower: 20, stats.SpellDamage: 20}, SpiritRegen: 0},
	}},
	161: {Name: "Defias Leather", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 5}, SpiritRegen: 0},
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	162: {Name: "Embrace of the Viper", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Intellect: 10}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.AttackPower: 10, stats.RangedAttackPower: 10}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	163: {Name: "Chain of the Scarlet Crusade", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ShadowResistance: 10}, SpiritRegen: 0},
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 1, stats.SpellHit: 1}, SpiritRegen: 0},
		6: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	181: {Name: "Magister's Regalia", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 18, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	182: {Name: "Vestments of the Devout", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 18, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	183: {Name: "Dreadmist Raiment", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 18, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	184: {Name: "Shadowcraft Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.AttackPower: 30, stats.RangedAttackPower: 30}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	185: {Name: "Wildheart Raiment", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.AttackPower: 30, stats.HealingPower: 18, stats.RangedAttackPower: 30, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	186: {Name: "Beaststalker Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.AttackPower: 30, stats.RangedAttackPower: 30}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	187: {Name: "The Elements", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 18, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	188: {Name: "Lightforge Armor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 18, stats.SpellDamage: 18}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MP5: 8}, SpiritRegen: 0},
	}},
	189: {Name: "Battlegear of Valor", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 8, stats.FireResistance: 8, stats.FrostResistance: 8, stats.NatureResistance: 8, stats.ShadowResistance: 8}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.Strength: 15}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	281: {Name: "Champion's Battlegear", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.AttackPower: 40, stats.RangedAttackPower: 40}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.Stamina: 20}, SpiritRegen: 0},
	}},
	321: {Name: "Imperial Plate", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Defense: 7}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 1, stats.SpellHit: 1}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: true, Stats: stats.Stats{stats.Strength: 20}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1, stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	345: {Name: "Champion's Threads", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.HealingPower: 23, stats.SpellDamage: 23}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.Stamina: 20}, SpiritRegen: 0},
	}},
	421: {Name: "Bloodvine Garb", Profession: proto.Profession(11), Bonuses: map[int32]foreverEquipmentBonus{
		3: {Supported: true, Stats: stats.Stats{stats.SpellCrit: 2}, SpiritRegen: 0},
	}},
	441: {Name: "Primal Batskin", Profession: proto.Profession(8), Bonuses: map[int32]foreverEquipmentBonus{
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
	442: {Name: "Blood Tiger Harness", Profession: proto.Profession(8), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1, stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	443: {Name: "Bloodsoul Embrace", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		3: {Supported: true, Stats: stats.Stats{stats.MP5: 12}, SpiritRegen: 0},
	}},
	444: {Name: "The Darksoul", Profession: proto.Profession(2), Bonuses: map[int32]foreverEquipmentBonus{
		3: {Supported: true, Stats: stats.Stats{stats.Defense: 20}, SpiritRegen: 0},
	}},
	467: {Name: "The Highlander's Resolution", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	468: {Name: "The Highlander's Resolve", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	469: {Name: "The Highlander's Determination", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	471: {Name: "The Highlander's Purpose", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	472: {Name: "The Highlander's Will", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	473: {Name: "The Highlander's Intent", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	483: {Name: "The Defiler's Determination", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	484: {Name: "The Defiler's Fortitude", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	485: {Name: "The Defiler's Intent", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	486: {Name: "The Defiler's Purpose", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	487: {Name: "The Defiler's Resolution", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 1}, SpiritRegen: 0},
	}},
	488: {Name: "The Defiler's Will", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.Stamina: 5}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.SpellCrit: 1}, SpiritRegen: 0},
	}},
	489: {Name: "Black Dragon Mail", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 1}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.MeleeCrit: 2}, SpiritRegen: 0},
		4: {Supported: true, Stats: stats.Stats{stats.FireResistance: 10}, SpiritRegen: 0},
	}},
	490: {Name: "Green Dragon Mail", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.MP5: 3}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{}, SpiritRegen: 0.15},
	}},
	491: {Name: "Blue Dragon Mail", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ArcaneResistance: 4, stats.FireResistance: 4, stats.FrostResistance: 4, stats.NatureResistance: 4, stats.ShadowResistance: 4}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.HealingPower: 28, stats.SpellDamage: 28}, SpiritRegen: 0},
	}},
	522: {Name: "Champion's Vestments", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.AttackPower: 40, stats.RangedAttackPower: 40}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.Stamina: 20}, SpiritRegen: 0},
	}},
	1968: {Name: "Blessed Plate", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.ShadowResistance: 10}, SpiritRegen: 0},
		3: {Supported: true, Stats: stats.Stats{stats.Strength: 20}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 2, stats.SpellHit: 2}, SpiritRegen: 0},
		6: {Supported: true, Stats: stats.Stats{stats.HolyPower: 29}, SpiritRegen: 0},
	}},
	2111: {Name: "The Spiritcaller's Storm", Profession: proto.Profession(0), Bonuses: map[int32]foreverEquipmentBonus{
		2: {Supported: true, Stats: stats.Stats{stats.MeleeHit: 1, stats.SpellHit: 1}, SpiritRegen: 0},
		3: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		4: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
		5: {Supported: false, Stats: stats.Stats{}, SpiritRegen: 0},
	}},
}
