#!/usr/bin/env python3
"""Compile directly represented Forever equipment-set effects from client tables."""

import argparse
import csv
import json
from pathlib import Path

BUILD = "1.60.1.69893"
PROFESSIONS = {0: 0, 171: 1, 164: 2, 333: 3, 202: 4, 182: 5, 165: 8, 186: 9, 393: 10, 197: 11}


def compile_effects(effects):
    stats, spirit = {}, 0
    def add(stat, value):
        stats[stat] = stats.get(stat, 0) + value
    for r in effects:
        effect, aura, misc = (int(r[k]) for k in ("Effect", "EffectAura", "EffectMiscValue_0"))
        value = float(r["EffectBasePointsF"])
        if effect != 6:
            return None
        if aura == 29 and 0 <= misc <= 4:
            add(("Strength", "Agility", "Stamina", "Intellect", "Spirit")[misc], value)
        elif aura in (99, 124, 52, 57, 54, 55):
            add({99: "AttackPower", 124: "RangedAttackPower", 52: "MeleeCrit",
                 57: "SpellCrit", 54: "MeleeHit", 55: "SpellHit"}[aura], value)
        elif aura == 290:
            add("MeleeCrit", value)
            add("SpellCrit", value)
        elif aura == 13 and misc == 126:
            add("SpellDamage", value)
        elif aura == 135:
            add("HealingPower", value)
        elif aura == 13 and misc in (2, 4, 8, 16, 32, 64):
            add({2: "HolyPower", 4: "FirePower", 8: "NaturePower", 16: "FrostPower",
                 32: "ShadowPower", 64: "ArcanePower"}[misc], value)
        elif aura == 22:
            for mask, stat in ((2, "HolyResistance"), (4, "FireResistance"), (8, "NatureResistance"),
                               (16, "FrostResistance"), (32, "ShadowResistance"), (64, "ArcaneResistance")):
                if misc & mask and stat != "HolyResistance":
                    add(stat, value)
        elif aura == 30 and misc == 95:
            add("Defense", value)
        elif aura == 85 and misc == 0 and int(r["EffectAuraPeriod"]) in (0, 5000):
            # Passive power regeneration is not periodic energize (aura 24).
            # 18378/21625/21636 have period=0 and explicit per-five-second text.
            add("MP5", value)
        elif aura == 134:
            spirit += value / 100
        else:
            return None
    return stats, spirit


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    args = parser.parse_args()
    catalog = json.loads(Path("assets/db_inputs/forever_gear_catalog.json").read_text())["items"]
    sets = {i["setId"]: i for i in catalog if i.get("setId")}
    definitions = {int(r["ID"]): r for r in csv.DictReader((args.cache / f"ItemSet_{BUILD}.csv").open())}
    spell_ids = {b["spellId"] for item in sets.values() for b in item["setBonuses"]}
    effects = {}
    for r in csv.DictReader((args.cache / f"SpellEffect_{BUILD}.csv").open()):
        if int(r["SpellID"]) in spell_ids:
            effects.setdefault(int(r["SpellID"]), []).append(r)
    output, code = {}, []
    for id, item in sorted(sets.items()):
        definition = definitions[id]
        skill = int(definition["RequiredSkill"])
        bonuses = {}
        for b in item["setBonuses"]:
            bonus = bonuses.setdefault(b["pieces"], {"spells": [], "stats": {}, "spiritRegen": 0, "supported": True})
            bonus["spells"].append(b["spellId"])
            parsed = compile_effects(effects.get(b["spellId"], [])) if b["spellId"] in effects else None
            if parsed is None or b["specialization"] or b["traitSubTree"]:
                bonus["supported"] = False
                continue
            stats, spirit = parsed
            bonus["spiritRegen"] += spirit
            for stat, value in stats.items():
                bonus["stats"][stat] = bonus["stats"].get(stat, 0) + value
        supported = skill in PROFESSIONS and int(definition["RequiredSkillRank"]) <= 300
        output[id] = {"name": definition["Name_lang"], "profession": PROFESSIONS.get(skill, -1), "bonuses": bonuses}
        code.append(f'{id}: {{Name: {json.dumps(definition["Name_lang"])}, Profession: proto.Profession({PROFESSIONS.get(skill, 0)}), Bonuses: map[int32]foreverEquipmentBonus{{')
        for pieces, b in sorted(bonuses.items()):
            values = ", ".join(f"stats.{stat}: {value:g}" for stat, value in sorted(b["stats"].items()))
            code.append(f'{pieces}: {{Supported: {str(supported and b["supported"]).lower()}, Stats: stats.Stats{{{values}}}, SpiritRegen: {b["spiritRegen"]:g}}},')
        code.append("}},")
    Path("assets/db_inputs/forever_equipment_sets.json").write_text(json.dumps({"clientBuild": BUILD, "sets": output}, indent=2) + "\n")
    Path("sim/core/forever_equipment_sets_generated.go").write_text(
        "// Code generated by tools/database/compile_forever_sets.py; DO NOT EDIT.\n"
        "package core\nimport (\n\"github.com/wowsims/classic/sim/core/proto\"\n"
        "\"github.com/wowsims/classic/sim/core/stats\"\n)\n"
        "var foreverEquipmentSets = map[int32]foreverEquipmentSet{\n" + "\n".join(code) + "\n}\n")
    print(f"Compiled {len(sets)} sets; {sum(b['supported'] for s in output.values() for b in s['bonuses'].values())} directly represented thresholds")


if __name__ == "__main__":
    main()
