#!/usr/bin/env python3
"""Validate and render the canonical mechanics/coverage register."""

import argparse
from collections import Counter
from html import escape
import json
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]
REGISTER = ROOT / "docs/uncertainties.json"
SOURCE_ROOT = "https://github.com/gunba/wow-forever-sim/blob/forever/"
STATUSES = {
    "needs-evidence": "Needs evidence",
    "needs-code": "Implementation gap",
    "model-choice": "Model assumption",
    "resolved": "Resolved",
    "out-of-scope": "Outside current scenarios",
}
KINDS = {"mechanic", "implementation", "scenario", "data"}
ACCESS = {
    "level20": "Level 20",
    "later": "Later access",
    "source-code": "Sources / code",
    "decision": "Model decision",
}
PRIORITIES = {"high", "medium", "low"}


def load_register(path=REGISTER):
    data = json.loads(Path(path).read_text())
    ids = set()
    for item in data["items"]:
        ident = item["id"]
        if ident in ids:
            raise ValueError(f"Duplicate uncertainty ID: {ident}")
        ids.add(ident)
        for field in ("title", "question", "current_model", "impact", "resolution"):
            if not isinstance(item.get(field), str) or not item[field].strip():
                raise ValueError(f"{ident}: missing {field}")
        if item["category"] not in data["categories"]:
            raise ValueError(f"{ident}: unknown category")
        if item["status"] not in STATUSES or item["kind"] not in KINDS:
            raise ValueError(f"{ident}: unknown status/kind")
        if item["priority"] not in PRIORITIES or item["access"] not in ACCESS:
            raise ValueError(f"{ident}: unknown priority/access")
        if not item.get("sources"):
            raise ValueError(f"{ident}: no evidence/code references")
        for source in item["sources"]:
            if source.startswith("https://"):
                continue
            if not (ROOT / source.split("#")[0]).is_file():
                raise ValueError(f"{ident}: missing source {source}")
        for other in item.get("related", []):
            if other == ident:
                raise ValueError(f"{ident}: self-reference")
    for item in data["items"]:
        if set(item.get("related", [])) - ids:
            raise ValueError(f'{item["id"]}: unknown related ID')
    return data


def source_url(source):
    return source if source.startswith("https://") else SOURCE_ROOT + quote(source, safe="/#")


def ordered_items(data):
    priority = {"high": 0, "medium": 1, "low": 2}
    return sorted(data["items"], key=lambda x: (
        x["status"] in {"resolved", "out-of-scope"},
        priority[x["priority"]], x["id"],
    ))


def markdown(data):
    counts = Counter(item["status"] for item in data["items"])
    lines = [
        "# Simulator questions and coverage",
        "",
        "<!-- Generated by tools/forever_bench/uncertainties.py. Edit uncertainties.json. -->",
        "",
        f"Reviewed against `{data['reviewed_revision']}`. {data['scope']}",
        "",
        "This is the current register. Earlier audits preserve historical findings, not current task status.",
        "An implementation gap is not a request to test an unknown game rule. Model assumptions are not measured facts.",
        "",
        " · ".join(f"{STATUSES[key]}: **{counts[key]}**" for key in STATUSES),
        "",
        "## Updating an answer",
        "",
        "Edit `docs/uncertainties.json`, retaining the ID and qualified legacy references. "
        "Record the evidence and resulting model/disposition; mark an item resolved only when its "
        "specific question is answered or its implementation gap is closed. Regenerate with "
        "`python3 tools/forever_bench/uncertainties.py`.",
        "",
        "Old T50, T51 and T52 labels were reused for different topics. The qualified aliases below "
        "preserve those references without conflating their answers. Private chat and identifying logs stay local.",
        "",
        "## Inventory coverage",
        "",
        *["- " + note for note in data["coverage"]],
        "",
    ]
    for category, label in data["categories"].items():
        lines += [f"## {label}", ""]
        for item in ordered_items(data):
            if item["category"] != category:
                continue
            lines += [
                f'### {item["id"]} — {item["title"]}',
                "",
                f'**{STATUSES[item["status"]]} · {item["priority"].title()} priority · {ACCESS[item["access"]]}**',
                "",
                f'**Question:** {item["question"]}',
                "",
                f'**Current model:** {item["current_model"]}',
                "",
                f'**Impact:** {item["impact"]}',
                "",
                f'**To close:** {item["resolution"]}',
                "",
                "**References:** " + " · ".join(
                    f"[{source}]({source_url(source)})" for source in item["sources"]),
                "",
            ]
            if item.get("legacy"):
                lines += ["**Earlier references:** " + "; ".join(item["legacy"]), ""]
            if item.get("related"):
                lines += ["**Related:** " + ", ".join(item["related"]), ""]
    return "\n".join(lines)


def render_html(data):
    """Self-contained, progressively enhanced register for the review page."""
    groups = []
    for category, label in data["categories"].items():
        cards = []
        items = [x for x in ordered_items(data) if x["category"] == category]
        for item in items:
            legacy = "; ".join(item.get("legacy", []))
            search = " ".join(str(item.get(k, "")) for k in (
                "id", "title", "question", "current_model", "impact", "resolution",
                "legacy", "category", "status", "priority", "access",
            ))
            links = " · ".join(
                f'<a href="{escape(source_url(src), quote=True)}">{escape(src)}</a>'
                for src in item["sources"])
            cards.append(
                f'<details class="question-card" id="{item["id"]}" '
                f'data-status="{item["status"]}" data-priority="{item["priority"]}" '
                f'data-access="{item["access"]}" data-search="{escape(search.casefold(), quote=True)}">'
                f'<summary><span class="question-id">{item["id"]}</span> {escape(item["title"])} '
                f'<span class="question-state">{STATUSES[item["status"]]} · {item["priority"]}</span></summary>'
                f'<p><strong>Question:</strong> {escape(item["question"])}</p>'
                f'<p><strong>Current model:</strong> {escape(item["current_model"])}</p>'
                f'<p><strong>Impact:</strong> {escape(item["impact"])}</p>'
                f'<p><strong>To close ({ACCESS[item["access"]]}):</strong> {escape(item["resolution"])}</p>'
                f'<p class="question-links">{links}</p>'
                + (f'<p class="note">Earlier references: {escape(legacy)}</p>' if legacy else "")
                + f'<a href="#{item["id"]}" class="note">Link to {item["id"]}</a></details>'
            )
        active = sum(x["status"] not in {"resolved", "out-of-scope"} for x in items)
        groups.append(
            f'<details class="question-group"><summary>{escape(label)} '
            f'<span class="question-count">{active} active / {len(items)} total</span></summary>'
            + "".join(cards) + "</details>")
    status_options = "".join(f'<option value="{key}">{label}</option>' for key, label in STATUSES.items())
    access_options = "".join(f'<option value="{key}">{label}</option>' for key, label in ACCESS.items())
    return (
        '<section id="questions" aria-labelledby="question-heading"><h2 id="question-heading">Questions &amp; coverage</h2>'
        '<p class="note">Current mechanics, modeling assumptions and implementation gaps. '
        'Open a category or search; resolved history is available separately.</p>'
        '<form class="question-filters" role="search" onsubmit="return false">'
        '<label>Find a question <input id="question-search" type="search" placeholder="Class, spell, ID…"></label>'
        '<label>Status <select id="question-status"><option value="active">Active</option>'
        '<option value="all">All statuses</option>' + status_options + '</select></label>'
        '<label>Priority <select id="question-priority"><option value="all">All priorities</option>'
        '<option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label>'
        '<label>Answer route <select id="question-access"><option value="all">All routes</option>'
        + access_options + '</select></label></form>'
        '<p id="question-results" class="note" aria-live="polite"></p>'
        + "".join(groups)
        + '<p class="note"><a href="uncertainties.md">Complete readable register</a> · '
        '<a href="uncertainties.json">Structured register</a></p></section>'
    )


CSS = """
#questions{margin:1.5rem 0 2rem}
.question-filters{display:flex;flex-wrap:wrap;gap:.8rem;align-items:end}
.question-filters label{display:flex;flex-direction:column;font-size:.9rem;gap:.25rem}
.question-filters input,.question-filters select{background:#242834;color:#eee;border:1px solid #68707e;padding:.5rem;border-radius:4px}
.question-group{margin:.5rem 0;border:1px solid #343945;border-radius:5px}
.question-group>summary{padding:.65rem;cursor:pointer;font-weight:600}
.question-count,.question-state{color:#acb6c8;font-weight:400;font-size:.82rem;margin-left:.6rem}
.question-card{padding:.55rem .9rem;border-top:1px solid #343945}
.question-card>summary{cursor:pointer}
.question-card p{margin:.6rem 0;max-width:1150px}
.question-id{color:#a9d8ff;font-variant-numeric:tabular-nums}
.question-links{font-size:.8rem;overflow-wrap:anywhere}
.question-card:target{outline:2px solid #a9d8ff;outline-offset:-2px}
[hidden]{display:none!important}
.resource-group{margin:.7rem 0}.resource-group>summary{cursor:pointer}
"""

SCRIPT = """
(() => {
 const root = document.querySelector('#questions');
 if (!root) return;
 const cards = [...root.querySelectorAll('.question-card')];
 const groups = [...root.querySelectorAll('.question-group')];
 const search = root.querySelector('#question-search'), status = root.querySelector('#question-status');
 const priority = root.querySelector('#question-priority'), access = root.querySelector('#question-access');
 function filter() {
   const terms = search.value.toLowerCase().trim().split(/\\s+/).filter(Boolean);
   let n = 0;
   for (const card of cards) {
     const d = card.dataset;
     const matches = (status.value === 'all' || (status.value === 'active'
       ? !['resolved','out-of-scope'].includes(d.status) : status.value === d.status))
       && (priority.value === 'all' || priority.value === d.priority)
       && (access.value === 'all' || access.value === d.access)
       && terms.every(term => d.search.includes(term));
     card.hidden = !matches;
     if (matches) n++;
   }
   for (const group of groups) {
     const visible = [...group.querySelectorAll('.question-card')].filter(c => !c.hidden).length;
     group.hidden = !visible;
     group.querySelector('.question-count').textContent = `${visible} shown`;
     if (terms.length && visible) group.open = true;
   }
   root.querySelector('#question-results').textContent = `${n} of ${cards.length} entries shown`;
 }
 function revealLink() {
   const card = cards.find(c => '#' + c.id === location.hash);
   if (!card) return;
   status.value = 'all'; priority.value = 'all'; access.value = 'all'; search.value = '';
   filter(); card.open = true; card.closest('.question-group').open = true;
   card.scrollIntoView({block:'nearest'});
 }
 for (const control of [search,status,priority,access]) control.addEventListener('input', filter);
 window.addEventListener('hashchange', revealLink);
 filter(); revealLink();
})();
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check the generated Markdown without changing it")
    args = parser.parse_args()
    data = load_register()
    output = ROOT / "docs/uncertainties.md"
    text = markdown(data) + "\n"
    if args.check:
        if not output.exists() or output.read_text() != text:
            raise SystemExit("docs/uncertainties.md is stale; regenerate it")
    else:
        output.write_text(text)
    print(f'{len(data["items"])} entries; ' + ", ".join(
        f"{key}={value}" for key, value in sorted(Counter(x["status"] for x in data["items"]).items())))


if __name__ == "__main__":
    main()
